### ISSUE TITLE
unbound memory problem

### ISSUE THREAD

**Issue by pmwkaa** [coleifer/sophy#9]
Origin: https://groups.google.com/forum/#!topic/sophia-database/nX5HbdF7mcE

Using sophy bindings and sophia 2.1 I try to load a several Gb file into a database but even after settings the memory limit the consumption grows without limit.

What I am doing wrong?

Here's more or less the code I use:

``` C
            from sophy import Sophia
            from msgpack import loads, dumps

            env = Sophia(db, auto_open=False)
            env.memory_limit = 1024 * 1024 * 1024
            env.open()

            posts = env.create_database('Post', 'u32')

            filepath = os.path.join('dump', 'Posts.xml')
            for data in iterate(filepath):
                 posts[int(data['Id'])] = dumps(data)
            env.close()
```

Can we please check that `memory.limit` is set correctly?
Thanks!

**Comment by coleifer** [comment]
Have you tried writing a simple script in c to verify the issue is in fact with Sophy and not Sophia itself?

**Comment by pmwkaa** [comment]
yes, memory limits are core functional to support checkpoints, i believe it is highly tested in Sophia and being used in production:
https://github.com/pmwkaa/sophia/blob/master/test/multithread/multithread.test.c#L265
https://github.com/pmwkaa/sophia/blob/master/test/multithread/multithread.test.c#L314
https://github.com/pmwkaa/sophia/blob/master/test/multithread/multithread.test.c#L360
https://github.com/pmwkaa/sophia/blob/master/test/generic/checkpoint.test.c

Can we check, that after env.open() is being called, env.memory_limit is passed correctly to `memory.limit`?

**Comment by pmwkaa** [comment]
In v2.2 memory_limit is moved from `memory.limit` to `db.name.memory_limit`, but this should be not the problem, since Sophy is binded to v2.1?

**Comment by coleifer** [comment]
I believe this setting is working correctly, because if I ask for it's value, I get the value I set:

``` python
In [4]: env = Sophia('/tmp/s-test', auto_open=False)

In [5]: env.memory_limit=1024*1024

In [6]: env.open()
Out[6]: True

In [7]: env.memory_limit
Out[7]: 1048576
```

As to the behavior of Sophia itself and what it may do with this memory limit, I cannot say, but to me it appears the setting works.

If I try to set it on an open environment I get an error that says you cannot set it when the env is online -- makes sense and shows that _something_ happens when we set it.

If I set it, open, then get it back, it shows the value I set leading me to believe the right thing is happening.
